# Generated by Django 5.2.7 on 2026-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pendingregistration_teammember_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.PositiveIntegerField(default=999, help_text='Display order within role (lower number = first)'),
        ),
    ]
