# Generated by Django 5.2.7 on 2026-04-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
