# Generated by Django 5.2.7 on 2026-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_pendingregistration_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='google_scholar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
