# Generated by Django 5.2.7 on 2026-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_pendingregistration_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
