# Generated by Django 5.2.7 on 2026-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_pendingregistration_institution_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('publication_link', models.URLField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker', models.CharField(default='Research Lab', max_length=100)),
                ('hero_title', models.CharField(default='DeepScope Research', max_length=200)),
                ('hero_subtitle', models.TextField(default='Advancing practical AI and systems research through collaborative projects, rigorous experimentation, and open technical contributions.')),
                ('hero_primary_label', models.CharField(default='View Projects', max_length=80)),
                ('hero_primary_url', models.CharField(default='/projects/', max_length=200)),
                ('hero_secondary_label', models.CharField(default='Join Us', max_length=80)),
                ('hero_secondary_url', models.CharField(default='/login/registered-member/', max_length=200)),
                ('about_title', models.CharField(default='About / Mission', max_length=120)),
                ('about_intro', models.TextField(default='DeepScope Research brings together researchers, builders, and students to design practical systems with measurable impact.')),
                ('about_mission', models.TextField(default='Our mission is to create transparent, reproducible, and useful research that bridges foundational ideas with real-world deployment.')),
                ('research_title', models.CharField(default='Research Areas', max_length=120)),
                ('research_areas', models.TextField(default='AI\nRobotics\nIoT\nAutonomous Systems', help_text='One item per line.')),
                ('featured_projects_title', models.CharField(default='Featured Projects', max_length=120)),
                ('featured_publications_title', models.CharField(default='Publications Preview', max_length=120)),
                ('team_preview_title', models.CharField(default='Team Preview', max_length=120)),
                ('news_title', models.CharField(default='News / Blog', max_length=120)),
                ('cta_title', models.CharField(default='Join / Collaborate', max_length=120)),
                ('cta_description', models.TextField(default='If you want to apply, collaborate, or explore new research ideas with us, get in touch.')),
                ('cta_primary_label', models.CharField(default='Apply', max_length=80)),
                ('cta_primary_url', models.CharField(default='/login/registered-member/', max_length=200)),
                ('cta_secondary_label', models.CharField(default='Contact', max_length=80)),
                ('cta_secondary_url', models.CharField(default='mailto:research@dscoperesearch.org', max_length=200)),
                ('footer_contact_title', models.CharField(default='Contact', max_length=120)),
                ('footer_email', models.EmailField(blank=True, default='research@dscoperesearch.org', max_length=254)),
                ('footer_social_title', models.CharField(default='Social', max_length=120)),
                ('footer_university_info', models.TextField(default='DeepScope Research | University Research Group')),
                ('news_items', models.TextField(blank=True, help_text='One update per line.')),
                ('footer_social_links', models.TextField(blank=True, help_text='One social link per line, e.g. LinkedIn https://...')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_projects', models.ManyToManyField(blank=True, related_name='featured_on_home', to='projects.project')),
                ('featured_team_members', models.ManyToManyField(blank=True, related_name='featured_on_home', to='projects.teammember')),
                ('featured_publications', models.ManyToManyField(blank=True, related_name='featured_on_home', to='projects.publication')),
            ],
        ),
    ]
