# Generated by Django 5.2.7 on 2026-04-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_publication_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='assigned_instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__icontains': 'Instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='projects.teammember'),
        ),
    ]
